<?php

namespace App\Console\Commands;

use App\Foundation\Modules\ManifestData;
use App\Foundation\Modules\ModuleRegistry;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

/**
 * Emits resources/js/generated/module-registry.ts — the committed map of bundled
 * first-party module frontends (CLAUDE.md §7). The source of truth is the modules
 * on DISK (ModuleRegistry::discovered()), not the central `modules` table: the Vite
 * build bundles from disk, and the CI staleness gate (--check) must run without a
 * database. Remote (third-party) module frontends are never baked here — their refs
 * arrive at runtime via /api/v1/bootstrap.
 */
class FrontendGenerateCommand extends Command
{
    protected $signature = 'zenon:frontend:generate
        {--check : Verify the committed registry is current without writing (CI staleness gate)}
        {--path= : Output path override (testing)}';

    protected $description = 'Generate the committed frontend module registry from discovered module manifests';

    public function handle(ModuleRegistry $registry): int
    {
        $withEntry = collect($registry->discovered())
            ->filter(fn (ManifestData $manifest): bool => $manifest->frontendEntry !== null)
            ->sortKeys(); // deterministic ordering → stable content and hash

        // A bundled entry must exist on disk or the Vite build breaks later with a
        // far less obvious error. Skip and warn; --check still fails on the diff.
        $entryExists = fn (ManifestData $manifest): bool => is_file(
            $manifest->path.DIRECTORY_SEPARATOR.$manifest->frontendEntry
        );
        $modules = $withEntry->filter($entryExists);
        $missing = $withEntry->reject($entryExists);

        foreach ($missing as $alias => $manifest) {
            $this->components->error(sprintf(
                "Skipping '%s': frontend entry '%s' not found in %s.",
                $alias,
                $manifest->frontendEntry,
                $manifest->path,
            ));
        }

        $content = $this->render($modules->all());

        $path = (string) ($this->option('path') ?? '');
        $path = $path !== '' ? $path : resource_path('js/generated/module-registry.ts');

        if ((bool) $this->option('check')) {
            $current = is_file($path) ? (string) file_get_contents($path) : null;

            if ($current === null || str_replace("\r\n", "\n", $current) !== $content) {
                $this->components->error(
                    'module-registry.ts is stale — run `php artisan zenon:frontend:generate` and commit the result.'
                );

                return self::FAILURE;
            }

            $this->components->info('module-registry.ts is up to date.');

            return self::SUCCESS;
        }

        File::ensureDirectoryExists(dirname($path));
        File::put($path, $content);

        $this->components->twoColumnDetail('Generated', $path);
        $this->components->twoColumnDetail('Bundled modules', (string) $modules->count());

        return self::SUCCESS;
    }

    /**
     * Pure function of the alias-sorted module map; always emits LF line endings.
     *
     * @param  array<string, ManifestData>  $modules
     */
    private function render(array $modules): string
    {
        $hash = sha1(json_encode(
            array_map(
                fn (ManifestData $manifest): array => [
                    'entry' => $manifest->frontendEntry,
                    'version' => $manifest->version,
                ],
                $modules,
            ),
            JSON_THROW_ON_ERROR,
        ));

        $entries = '';

        foreach ($modules as $alias => $manifest) {
            $key = preg_match('/^[A-Za-z_$][A-Za-z0-9_$]*$/', $alias) === 1 ? $alias : "'{$alias}'";
            $import = '@modules/'.$manifest->name.'/'.preg_replace(
                '/\.(tsx|ts|jsx|js)$/',
                '',
                (string) $manifest->frontendEntry,
            );

            $entries .= "    {$key}: {\n";
            $entries .= "        source: 'bundled',\n";
            $entries .= "        load: () => import('{$import}'),\n";
            $entries .= "    },\n";
        }

        $map = $entries === ''
            ? "export const moduleRegistry: Record<string, RegistryEntry> = {};\n"
            : "export const moduleRegistry: Record<string, RegistryEntry> = {\n{$entries}};\n";

        return "/* AUTO-GENERATED by `php artisan zenon:frontend:generate` — DO NOT EDIT.\n"
            ." * Bundled first-party module frontends (CLAUDE.md §7). Remote (third-party)\n"
            ." * entries are NOT baked here — they arrive at runtime via /api/v1/bootstrap.\n"
            ." * CI fails when this file is stale (zenon:frontend:generate --check).\n"
            ." */\n"
            ."import type { RegistryEntry } from '@zenon/core/moduleTypes';\n"
            ."\n"
            .$map
            ."\n"
            ."export const registryHash = '{$hash}';\n";
    }
}
